package com.rn.wifi.p2p.core

enum class Event(val eventName: String) {
  PEERS_UPDATED("PEERS_UPDATED"),
  CONNECTION_INFO_UPDATED("CONNECTION_INFO_UPDATED"),
  THIS_DEVICE_CHANGED_ACTION("THIS_DEVICE_CHANGED_ACTION"),
  MESSAGE_RECEIVED("MESSAGE_RECEIVED"),
}
